# Generated by Django 4.0.4 on 2022-05-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='views',
        ),
        migrations.RemoveField(
            model_name='question',
            name='views',
        ),
    ]
