# Generated by Django 4.0.4 on 2022-04-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeanswer',
            name='mark_d',
            field=models.IntegerField(blank=True, choices=[('1', 'DisLike'), ('-1', 'UnDislike')], null=True),
        ),
        migrations.AlterField(
            model_name='likeanswer',
            name='mark_l',
            field=models.IntegerField(blank=True, choices=[('1', 'Like'), ('-1', 'UnLike')], null=True),
        ),
        migrations.AlterField(
            model_name='likequestion',
            name='mark_d',
            field=models.IntegerField(blank=True, choices=[('1', 'DisLike'), ('-1', 'UnDislike')], null=True),
        ),
        migrations.AlterField(
            model_name='likequestion',
            name='mark_l',
            field=models.IntegerField(blank=True, choices=[('1', 'Like'), ('-1', 'UnLike')], null=True),
        ),
    ]
