# Generated by Django 4.0.4 on 2022-05-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questions',
            field=models.ManyToManyField(related_name='questions_answers', to='app.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
