# Generated by Django 4.0.4 on 2022-05-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_answer_questions_alter_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
