# Generated by Django 4.0.4 on 2022-05-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_answer_question_answer_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionToAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'question_answer',
                'verbose_name_plural': 'questions_answers',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(to='app.questiontoanswer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='questions',
            field=models.ManyToManyField(to='app.questiontoanswer'),
        ),
    ]
